# Generated by Django 3.2.25 on 2025-02-18 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='content',
            field=models.TextField(max_length=500),
        ),
    ]
