# Generated by Django 3.2.25 on 2025-02-09 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20250209_0446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantitem',
            old_name='plant_name',
            new_name='name',
        ),
    ]
