# Generated by Django 3.2.25 on 2025-02-14 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_plant_name_plantitem_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantitem',
            name='img_alt',
        ),
    ]
