# Generated by Django 3.2.25 on 2025-02-15 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0006_auto_20250215_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantitem',
            name='rating',
        ),
        migrations.CreateModel(
            name='ReviewRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_body', models.CharField(max_length=500)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[100, None], upload_to='media')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(default=0)),
                ('plant_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.plantitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
