# Generated by Django 3.2.25 on 2025-02-16 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20250215_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='plant_item',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='reviewrating',
            old_name='user',
            new_name='reviewer',
        ),
    ]
