# Generated by Django 3.2.25 on 2025-02-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20250216_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='rating',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
