# Generated by Django 3.2.25 on 2025-02-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_reviewrating_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
