# Generated by Django 3.2.25 on 2025-02-21 05:19

from django.db import migrations
import django.utils.timezone
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_reviewrating_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantitem',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default=django.utils.timezone.now, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[400, None], upload_to='media'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[100, None], upload_to='media'),
        ),
    ]
