# Generated by Django 3.2.25 on 2025-02-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_reviewrating_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='created_on',
            field=models.DateField(auto_now=True),
        ),
    ]
