# Generated by Django 4.2 on 2025-02-24 20:05

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20250222_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[250, None], upload_to='reviews'),
        ),
    ]
