# Generated by Django 4.2 on 2025-02-24 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_reviewrating_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantitem',
            name='category',
            field=models.ForeignKey(default='3', on_delete=django.db.models.deletion.SET_DEFAULT, to='products.category'),
        ),
    ]
